# [.github/workflows/CI.yml]
name: CI
on:
  push:
    branches:
      - main 
    tags: '*'
  pull_request:
env:
  PINECONE_API_KEY: ${{ secrets.PINECONEAPIKEY }}
jobs:
  ubuntu:
    name: Julia ${{ matrix.version }} - ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.6'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
         CODECOV_TOKEN: ${{ secrets.CODECOVAPIKEY }}
      - uses: codecov/codecov-action@v2
  mac:
    name: Julia ${{ matrix.version }} - mac
    needs: ubuntu
    runs-on: macos-latest
    strategy:
      matrix:
        version:
          - '1.6'
        os:
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
         CODECOV_TOKEN: ${{ secrets.CODECOVAPIKEY }}
      - uses: codecov/codecov-action@v2
  windows:
      name: Julia ${{ matrix.version }} - windows
      needs: [ubuntu,mac]
      runs-on: windows-latest
      strategy:
        matrix:
          version:
            - '1.6'
          os:
            - windowsos-latest
          arch:
            - x64
      steps:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@latest
        - uses: julia-actions/julia-uploadcodecov@latest
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOVAPIKEY }}
        - uses: codecov/codecov-action@v2